server:
  port: 9015

spring:
  mvc:
    cors:
      enabled: true
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600

aichat:
  proxies:
    - id: "kimi"
      name: "moonshot kimi"
      chat-service:
        chat-completions-url: "https://api.moonshot.cn/v1/chat/completions"
      file-service:
        file-upload-url: "https://api.moonshot.cn/v1/files"
        file-query-url: "https://api.moonshot.cn/v1/files/{file_id}"
        file-content-url: "https://api.moonshot.cn/v1/files/{file_id}/content"
      authentications:
       - organization-id: "cou9h12vk6gfi4q7fn9g"
         key: "sk-pjqP8Ei2jqc4U72eArd8p1AOhozPgn76KEl3gjTR9Q8nQd27"
    - id: "deepseek"
      name: "deepseek"
      chat-service:
        chat-completions-url: "https://api.deepseek.com/v1/chat/completions"
      file-service:
        file-upload-url: "https://api.deepseek.com/v1/files"
        file-query-url: "https://api.deepseek.com/v1/files/{file_id}"
        file-content-url: "https://api.deepseek.com/v1/files/{file_id}/content"
      authentications:
        - organization-id: "ai-diagnose"
          key: "sk-a89b0420ced542159d62a608bb930ea2"

auth:
  token: "kimi-YRGWER8WQGkjwdc1QH2ZAPHCN0xbfeyQ"