server:
  port: 9015

aichat:
  proxies:
    - id: "kimi"
      name: "moonshot kimi"
      chat-service:
        chat-completions-url: "https://api.moonshot.cn/v1/chat/completions"
      file-service:
        file-upload-url: "https://api.moonshot.cn/v1/files"
        file-query-url: "https://api.moonshot.cn/v1/files/{file_id}"
        file-content-url: "https://api.moonshot.cn/v1/files/{file_id}/content"
      authentications:
        - organization-id: "xxxx"  # 此处填写 kimi 的 organization id
          key: "sk-xxxxx"          # 此处 kimi 填写密钥
    - id: "deepseek"
      name: "deepseek"
      chat-service:
        chat-completions-url: "https://api.deepseek.com/v1/chat/completions"
      file-service:
        file-upload-url: "https://api.deepseek.com/v1/files"
        file-query-url: "https://api.deepseek.com/v1/files/{file_id}"
        file-content-url: "https://api.deepseek.com/v1/files/{file_id}/content"
      authentications:
        - organization-id: "ai-diagnose" # 此处填写项目名
          key: "sk-xxxxxx"               # 此处填写 deepseek 密钥
    - id: "bailian-dashboard"
      name: "aliyun bailian dashboard"
      dashboard-api: true                # 此处使用的是阿里百炼大模型的 dashboard api
      authentications:
        - organization-id: "llm-xxxxxx"
          key: "sk-xxxxxx"

alibaba-cloud:
  sam-secret:
    # 请参考：https://help.aliyun.com/zh/ram/user-guide/create-an-accesskey-pair
    access-key-id: "xxxx"     # 许可ID
    access-key-secret: "xxxx" # 许可密钥
  service-region:
    # 请参考 https://api.aliyun.com/product/bailian
    region-id: "ap-southeast-1"
    end-point: "bailian.ap-southeast-1.aliyuncs.com"

bailian-knowledge-base: # 百炼大模型知识库
  workspace-id: "llm-xxxx" # 业务空间ID
  index-id: "xxxxx"     # 知识库ID
